import useLanguageChooser from "../helpers/hooks/useLanguageChooser";

export default class TEXT {
    persons  = useLanguageChooser('Personen', 'Servings')
    nutrients = useLanguageChooser('Voedingswaarden', 'Nutrients')
    daily = useLanguageChooser('Van dagelijkse behoefte', 'Of daily need')
    ingredients = useLanguageChooser('Ingrediënten', 'Ingredients')
    instructions = useLanguageChooser('Bereidingswijze', 'Instructions')
    loading = useLanguageChooser('Laden...', 'Loading...')
    noRecipe = useLanguageChooser('Er kan geen recept gevonden worden.', 'No recipe could be found.')
    getDataError = useLanguageChooser("Recept ophalen mislukt', 'Couldn't fetch recipe")
    noInstructions = useLanguageChooser('Geen instructies beschikbaar.', 'No instructions available.')
    welcome = useLanguageChooser('Welkom', 'Welcome')
    required = useLanguageChooser('Moet ingevoerd worden', 'Must be filled in')
    change = useLanguageChooser('Wijzigen', 'Change')
    emailMessage = useLanguageChooser('Voer een juist email-adres in', 'Email address is not correct')
    changeEmail = useLanguageChooser('Email wijzigen:', 'Change email:')
    changePassword = useLanguageChooser('Wijzig wachtwoord:', 'Change password:')
    old = useLanguageChooser('Oud:', 'Old:')
    passwordMessage = useLanguageChooser('Moet minimaal 1 hoofdletter, cijfer en 8 characters bevatten', 'Must contain 1 capital letter, number and 8 characters')
    new = useLanguageChooser('Nieuw:', 'New:')
    passwordMatch = useLanguageChooser('Wachtwoord is niet gelijk', 'The passwords do not match')
    repeat = useLanguageChooser('Herhaald:', 'Repeat:')
    dark = useLanguageChooser('Donker', 'Dark')
    light = useLanguageChooser('Licht', 'Light')
    wrongPassword = useLanguageChooser('Wachtwoord is verkeerd', 'Wrong password')
    username = useLanguageChooser('Gebruikersnaam', 'Username')
    password = useLanguageChooser('Wachtwoord:', 'Password:')
    errorIngredients = useLanguageChooser('Kan geen recept opgehaald worden.', 'Recipes cant be fetched.')
    searchIngredients = useLanguageChooser('Voer ingrediënten in', 'Search ingredients')
    grocery = useLanguageChooser('Boodschappenlijst', 'Grocery list')
    productError = useLanguageChooser('Producten kunnen niet opgehaald worden', "Products can't be fetched")
    fridge = useLanguageChooser('Koelkast', 'Fridge')
    register = useLanguageChooser('Registreer', 'Register')
    email = useLanguageChooser('Voer een juist email-adres in', 'Email address is not correct')
    manual = useLanguageChooser('Gebruiksaanwijzing', 'Manual')
    profile = useLanguageChooser('Profiel', 'Profile')
    succes = useLanguageChooser('Gelukt!', 'Succes')
    failedOldPassword = useLanguageChooser('Oude wachtwoord incorrect', 'Old password incorrect')
    failedSamePassword = useLanguageChooser('Wachtwoorden zijn hetzelfde', 'Passwords are the same')
    failedUsername = useLanguageChooser('Gebruiker bestaat al', 'User already exists')
    failedEmail = useLanguageChooser('Email al in gebruik', 'Email already in use')
    failedUnknown = useLanguageChooser('Er is een fout opgetreden', 'An error has occurred')
    homepage = useLanguageChooser('Verspil me niet!', 'Dont waste me!')
    recipe = useLanguageChooser('Recepten', 'Recipes')
    search = useLanguageChooser('Zoeken', 'Search')
};